apiVersion: v1
kind: Service
metadata:
  name: spring-boot-newbus-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: spring-boot-newbus
  type: NodePort