apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbuss-deployment
  labels:
    app: spring-boot-newbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-newbus
  template:
    metadata:
      labels:
        app: spring-boot-newbus
    spec:
      containers:
        - image: newbus-service:latest
          name: newbus-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            failureThreshold: 5
